# Generated by Django 5.2.3 on 2025-09-19 19:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_booking_number'),
        ('hrms', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_role', models.CharField(choices=[('caretaker', 'Caretaker'), ('accommodation_staff', 'Accommodation Staff'), ('wellness_specialist', 'Wellness Specialist'), ('meditation_instructor', 'Meditation Instructor'), ('mental_health_counselor', 'Mental Health Counselor'), ('food_provider', 'Food Provider'), ('supervisor', 'Supervisor'), ('quality_controller', 'Quality Controller'), ('customer_service', 'Customer Service'), ('trainer', 'Trainer')], max_length=50)),
                ('specializations', models.JSONField(blank=True, default=list, help_text='List of specializations or skills')),
                ('service_areas', models.JSONField(blank=True, default=list, help_text='Geographic or service areas covered')),
                ('assignment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('service_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average service rating from customers', max_digits=3)),
                ('completed_assignments', models.IntegerField(default=0)),
                ('total_service_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available_days', models.JSONField(default=list, help_text='Days of week available (0=Monday, 6=Sunday)')),
                ('available_hours', models.JSONField(default=dict, help_text='Available hours per day {day: [start_hour, end_hour]}')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List of certifications relevant to vendor services')),
                ('training_completed', models.JSONField(blank=True, default=list, help_text='List of completed training programs')),
                ('work_permit_number', models.CharField(blank=True, max_length=50)),
                ('work_permit_expiry', models.DateField(blank=True, null=True)),
                ('visa_status', models.CharField(blank=True, max_length=100)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_staff_assignments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='hrms.employeeprofile')),
                ('vendor_profile', models.ForeignKey(help_text='Vendor this employee is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Staff Assignment',
                'verbose_name_plural': 'Vendor Staff Assignments',
                'unique_together': {('employee', 'vendor_profile')},
            },
        ),
        migrations.CreateModel(
            name='ServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='assigned', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('service_notes', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('customer_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('customer_feedback', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_services', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='bookings.booking')),
                ('vendor_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='hrms.vendorstaff')),
            ],
            options={
                'verbose_name': 'Service Assignment',
                'verbose_name_plural': 'Service Assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorStaffTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='enrolled', max_length=20)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Training score/grade', max_digits=5, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('certificate_expiry', models.DateField(blank=True, null=True)),
                ('trainer_notes', models.TextField(blank=True)),
                ('participant_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_staff_enrollments', to='hrms.trainingprogram')),
                ('vendor_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='hrms.vendorstaff')),
            ],
            options={
                'verbose_name': 'Vendor Staff Training',
                'verbose_name_plural': 'Vendor Staff Training Records',
                'unique_together': {('vendor_staff', 'training_program')},
            },
        ),
    ]
