# Generated by Django 5.2.3 on 2025-09-19 06:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0003_journalentry_ledgeraccount_journalline"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Balance",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to="financial.ledgeraccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger Balance",
                "verbose_name_plural": "Ledger Balances",
            },
        ),
    ]
