# Generated by Django 5.2.3 on 2025-09-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0004_ledgerbalance"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgeraccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("asset", "Asset"),
                    ("liability", "Liability"),
                    ("equity", "Equity"),
                    ("revenue", "Revenue"),
                    ("expense", "Expense"),
                ],
                default="asset",
                max_length=20,
                verbose_name="Account Type",
            ),
        ),
    ]
