# Generated by Django 5.2.3 on 2025-09-19 07:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0005_ledgeraccount_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingcategory",
            name="is_cogs",
            field=models.BooleanField(default=False, verbose_name="Is COGS"),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="cost_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Cost Amount",
            ),
        ),
    ]
