# Generated by Django 5.2.3 on 2025-09-20 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0008_currencyrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="valid_from",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Valid From"
            ),
        ),
        migrations.AddIndex(
            model_name="currencyrate",
            index=models.Index(
                fields=["from_currency", "to_currency", "valid_from"],
                name="financial_c_from_cu_8dcf29_idx",
            ),
        ),
    ]
