# Generated by Django 5.2.3 on 2025-09-17 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wellness/categories/', verbose_name='Image')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='Icon Class')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Wellness Category',
                'verbose_name_plural': 'Wellness Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WellnessProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Program Name')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=200, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('benefits', models.TextField(blank=True, verbose_name='Benefits')),
                ('duration', models.IntegerField(default=60, verbose_name='Duration (minutes)')),
                ('image', models.ImageField(upload_to='wellness/programs/', verbose_name='Image')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True, verbose_name='Video URL')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('coming_soon', 'Coming Soon')], default='active', max_length=20, verbose_name='Status')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='wellness.wellnesscategory', verbose_name='Category')),
                ('provider', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['WELLNESS', 'MEDITATION', 'MENTAL_HEALTH']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellness_programs', to=settings.AUTH_USER_MODEL, verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Wellness Program',
                'verbose_name_plural': 'Wellness Programs',
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WellnessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Session Title')),
                ('date', models.DateField(verbose_name='Session Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('online_link', models.URLField(blank=True, null=True, verbose_name='Online Meeting Link')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online Session')),
                ('max_participants', models.IntegerField(default=10, verbose_name='Maximum Participants')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='wellness.wellnessprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Wellness Session',
                'verbose_name_plural': 'Wellness Sessions',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WellnessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='wellness.wellnessprogram', verbose_name='Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wellness Review',
                'verbose_name_plural': 'Wellness Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'program')},
            },
        ),
        migrations.CreateModel(
            name='WellnessEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='enrolled', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='wellness.wellnessprogram', verbose_name='Program')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='wellness.wellnesssession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Wellness Enrollment',
                'verbose_name_plural': 'Wellness Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'session')},
            },
        ),
    ]
