# Generated by Django 5.2.3 on 2025-09-19 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vendor_profile',
            field=models.ForeignKey(blank=True, help_text='The vendor/service provider offering this service', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vendors.vendorprofile', verbose_name='Vendor'),
        ),
    ]
