# Generated by Django 5.2.3 on 2025-09-19 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='Business Name')),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('small_business', 'Small Business'), ('corporation', 'Corporation'), ('ngo', 'NGO/Non-Profit')], max_length=20, verbose_name='Business Type')),
                ('business_license', models.CharField(blank=True, max_length=100, verbose_name='Business License')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID')),
                ('business_phone', models.CharField(max_length=20, verbose_name='Business Phone')),
                ('business_email', models.EmailField(max_length=254, verbose_name='Business Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('service_areas', models.TextField(help_text='Areas where you provide services', verbose_name='Service Areas')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20, verbose_name='Status')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total Reviews')),
                ('total_bookings', models.PositiveIntegerField(default=0, verbose_name='Total Bookings')),
                ('completed_bookings', models.PositiveIntegerField(default=0, verbose_name='Completed Bookings')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Commission Rate')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Earnings')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='Joined Date')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Last Active')),
                ('auto_accept_bookings', models.BooleanField(default=False, verbose_name='Auto Accept Bookings')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('notification_sms', models.BooleanField(default=True, verbose_name='SMS Notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('commission', 'Commission Payment'), ('bonus', 'Performance Bonus'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20, verbose_name='Payment Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='QAR', max_length=3, verbose_name='Currency')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('booking_count', models.PositiveIntegerField(default=0, verbose_name='Bookings Count')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gross Amount')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Commission Rate')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Payment',
                'verbose_name_plural': 'Vendor Payments',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license', 'Business License'), ('insurance', 'Insurance Certificate'), ('certification', 'Professional Certification'), ('tax_certificate', 'Tax Certificate'), ('identity', 'Identity Document'), ('other', 'Other')], max_length=20, verbose_name='Document Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('document_file', models.FileField(upload_to='vendor_documents/', verbose_name='Document File')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded Date')),
                ('verified_date', models.DateTimeField(blank=True, null=True, verbose_name='Verified Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Document',
                'verbose_name_plural': 'Vendor Documents',
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorBlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('reason', models.CharField(max_length=200, verbose_name='Reason')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackout_dates', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Blackout Date',
                'verbose_name_plural': 'Vendor Blackout Dates',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, verbose_name='Day of Week')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Availability',
                'verbose_name_plural': 'Vendor Availability',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('vendor', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='VendorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('bookings_received', models.PositiveIntegerField(default=0, verbose_name='Bookings Received')),
                ('bookings_accepted', models.PositiveIntegerField(default=0, verbose_name='Bookings Accepted')),
                ('bookings_completed', models.PositiveIntegerField(default=0, verbose_name='Bookings Completed')),
                ('bookings_cancelled', models.PositiveIntegerField(default=0, verbose_name='Bookings Cancelled')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('commission_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission Paid')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating')),
                ('response_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Avg Response Time (min)')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Analytics',
                'verbose_name_plural': 'Vendor Analytics',
                'ordering': ['-date'],
                'unique_together': {('vendor', 'date')},
            },
        ),
    ]
