# Generated by Django 5.2.3 on 2025-10-10 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocpoolDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Department',
                'verbose_name_plural': 'Document Departments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocpoolDocumentBorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Border',
                'verbose_name_plural': 'Document Borders',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocpoolDocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocpoolDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocpoolDocumentSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='docpool.docpooldocumentcategory')),
            ],
            options={
                'verbose_name': 'Document Sub-Category',
                'verbose_name_plural': 'Document Sub-Categories',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DocpoolReferenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docpool.docpooldepartment')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docpool.docpooldocumenttype')),
            ],
            options={
                'verbose_name': 'Reference Number',
                'verbose_name_plural': 'Reference Numbers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocpoolDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docpool/documents/%Y/%m/%d/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='internal', max_length=20)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for searching')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docpool.docpooldepartment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docpool_uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('border', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docpool.docpooldocumentborder')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docpool.docpooldocumentcategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docpool.docpooldocumentsubcategory')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docpool.docpooldocumenttype')),
                ('reference_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docpool.docpoolreferencenumber')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocpoolSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('department_filter', models.CharField(blank=True, max_length=10)),
                ('document_type_filter', models.CharField(blank=True, max_length=10)),
                ('year_filter', models.PositiveIntegerField(blank=True, null=True)),
                ('border_filter', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocpoolDocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('access_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='docpool.docpooldocument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Access Log',
                'verbose_name_plural': 'Document Access Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['document', 'timestamp'], name='docpool_doc_documen_da9086_idx'), models.Index(fields=['user', 'timestamp'], name='docpool_doc_user_id_c1cfca_idx'), models.Index(fields=['access_type'], name='docpool_doc_access__b584cd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='docpoolreferencenumber',
            index=models.Index(fields=['year', 'month', 'department', 'document_type'], name='docpool_doc_year_d44bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='docpoolreferencenumber',
            index=models.Index(fields=['reference_number'], name='docpool_doc_referen_f9611b_idx'),
        ),
        migrations.AddIndex(
            model_name='docpooldocument',
            index=models.Index(fields=['year'], name='docpool_doc_year_f3e4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='docpooldocument',
            index=models.Index(fields=['month'], name='docpool_doc_month_cb9ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='docpooldocument',
            index=models.Index(fields=['border'], name='docpool_doc_border__274c77_idx'),
        ),
        migrations.AddIndex(
            model_name='docpooldocument',
            index=models.Index(fields=['document_type'], name='docpool_doc_documen_8f9737_idx'),
        ),
        migrations.AddIndex(
            model_name='docpooldocument',
            index=models.Index(fields=['department'], name='docpool_doc_departm_f3ff09_idx'),
        ),
        migrations.AddIndex(
            model_name='docpooldocument',
            index=models.Index(fields=['category'], name='docpool_doc_categor_e24398_idx'),
        ),
        migrations.AddIndex(
            model_name='docpooldocument',
            index=models.Index(fields=['subcategory'], name='docpool_doc_subcate_dfeb44_idx'),
        ),
        migrations.AddIndex(
            model_name='docpooldocument',
            index=models.Index(fields=['access_level'], name='docpool_doc_access__1d9e77_idx'),
        ),
        migrations.AddIndex(
            model_name='docpooldocument',
            index=models.Index(fields=['is_active'], name='docpool_doc_is_acti_031cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='docpooldocument',
            index=models.Index(fields=['uploaded_at'], name='docpool_doc_uploade_dd5640_idx'),
        ),
        migrations.AddIndex(
            model_name='docpoolsearchlog',
            index=models.Index(fields=['timestamp'], name='docpool_doc_timesta_6625db_idx'),
        ),
        migrations.AddIndex(
            model_name='docpoolsearchlog',
            index=models.Index(fields=['user'], name='docpool_doc_user_id_fe4399_idx'),
        ),
        migrations.AddIndex(
            model_name='docpoolsearchlog',
            index=models.Index(fields=['query'], name='docpool_doc_query_25163e_idx'),
        ),
    ]
