# Generated by Django 5.2.3 on 2025-09-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
    ]
