# Generated by Django 5.2.3 on 2025-09-18 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20250918_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Additional Fees'),
        ),
        migrations.AddField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base Price'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True, verbose_name='Booking Number'),
        ),
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Client Email'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Client Phone'),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At'),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact'),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Emergency Phone'),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='booking',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Special Instructions'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('bnpl', 'Buy Now Pay Later')], max_length=20, verbose_name='Payment Method')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Booking Payment',
                'verbose_name_plural': 'Booking Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Old Status')),
                ('new_status', models.CharField(max_length=20, verbose_name='New Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking', verbose_name='Booking')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
            ],
            options={
                'verbose_name': 'Booking Status History',
                'verbose_name_plural': 'Booking Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
