# Generated by Django 5.2.3 on 2025-09-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_additional_fees_booking_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Booking Number'),
        ),
    ]
