name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ copilot/**, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests (settings_dev)
      env:
        HAWWA_ALLOWED_HOSTS: localhost,127.0.0.1,testserver
        HAWWA_DB_PATH: ${{ github.workspace }}/db.sqlite3
        HAWWA_EMAIL_BACKEND: django.core.mail.backends.locmem.EmailBackend
      run: |
        python manage.py test --settings=hawwa.settings_dev -v 1
